---
logging:
  level:
    ROOT: info
    de.codecentric: trace
    org.springframework.web: debug
  file:
    name: "build/hello-spring-boot-3.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  info:
    java:
      enabled: true
      env:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  server:
    port: 9091

spring:
  application:
    name: hello-spring-boot-3
  boot:
    admin:
      client:
        url: http://localhost:8080
  jmx:
    enabled: true
  main:
    lazy-initialization: true
server:
  port: 9090

