management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always
        shutdown:
            enabled: true

    endpoints:
        web:
            exposure:
                include: '*'

    info:
        build:
            enabled: true
        env:
            enabled: true
        git:
            enabled: true
        java:
            enabled: true

    server:
        port: 9081

server:
    port: 9080

spring:
    boot:
        admin:
            client:
                url: http://localhost:8080
    jmx:
        enabled: true
