---
logging:
  level:
    ROOT: info
    de.codecentric: trace
    org.springframework.web: debug
  file:
    name: "target/spring-boot-admin-filtering-notifier.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  info:
    java:
      enabled: true
      env:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

spring:
  application:
    name: spring-boot-admin-filtering-notifier
  jmx:
    enabled: true
  main:
    lazy-initialization: true

---
# tag::customization-external-views[]
spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  boot:
    admin:
      ui:
        external-views:
          - label: "🚀"
            url: https://codecentric.de
            order: 2000
      # context-path: test/
      client:
        url: http://localhost:8080
      notify:
        mail:
          to: <your.email@gmail.com>
          from: <whatever@gmail.com>
          enabled: true
# end::customization-external-views[]
---
