---
name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Run build and test spring-boot-admin-3
        run: |
          ./gradlew clean build
        working-directory: spring-boot-admin-3
      - name: Run build and test hello-spring-boot-admin-3
        run: |
          ./gradlew clean build
        working-directory: hello-spring-boot-admin-3
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./build/jacoco
          verbose: true # optional (default = false)

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: build/reports/tests/test
